services:
  db:
    image: mysql:latest
    container_name: gawdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: alumnos
      MYSQL_USER: developer
      MYSQL_PASSWORD: contraps
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
